# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy to AWS

on:
  workflow_run:
    workflows: [Test Cases]
    branches: [main]
    types:
      - completed

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{secrets.AWS_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies using virtual environment
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          deactivate
          echo "PACKAGE_NAME=`date +%Y%m%d`.zip" >> $GITHUB_ENV
      - name: Prepare deployment package
        run: |
          cp -r .env/lib64/python3.9/site-packages/* .
          rm -r .env
          rm -r .github
          rm -r tests
          zip -r $PACKAGE_NAME .
      - name: Upload deployment package to AWS S3
        env:
          BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 cp $PACKAGE_NAME "s3://$BUCKET_NAME/"
      - name: Deploy to AWS lambda
        env:
          BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        run: |
          aws lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket $BUCKET_NAME --s3-key $PACKAGE_NAME --publish
